import type { Place } from "@memento-mori/types";

export const SEED_PLACES: Place[] = [
  // ── Europe ──────────────────────────────────────────────────────────────
  {
    id: "1",
    name: "Hoia-Baciu Forest",
    slug: "hoia-baciu-forest",
    lat: 46.7739,
    lng: 23.5169,
    category: "CURSED_PLACE",
    country: "Romania",
    city: "Cluj-Napoca",
    description:
      "Known as the Bermuda Triangle of Romania — a forest where electronics fail, compasses spin, and visitors vanish.",
    legend:
      "Locals refuse to enter the forest fearing they will never return. Those who do often report intense anxiety, nausea, and strange rashes. The trees grow in bizarre twisted shapes, and electronic equipment frequently malfunctions. In 1968, biologist Alexandru Sift photographed a UFO hovering above the clearing now known as the Round Clearing — a perfectly circular area where nothing grows.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Greyfriars Kirkyard",
    slug: "greyfriars-kirkyard",
    lat: 55.9467,
    lng: -3.1919,
    category: "CEMETERY",
    country: "Scotland",
    city: "Edinburgh",
    description:
      "A 16th-century churchyard home to the infamous MacKenzie Poltergeist — responsible for over 500 documented attacks.",
    legend:
      "Sir George MacKenzie, known as 'Bluidy Mackenzie' for his brutal persecution of Covenanters, is buried here. Since a homeless man broke into his mausoleum in 1999, over 500 people have reported being scratched, bitten, and knocked unconscious near his tomb. Locked ghost tours operate nightly — more people have been harmed here than anywhere else on record.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Château de Brissac",
    slug: "chateau-de-brissac",
    lat: 47.3597,
    lng: -0.4432,
    category: "HAUNTED_HOUSE",
    country: "France",
    city: "Brissac-Quincé",
    description:
      "The tallest castle in France, haunted by La Dame Verte — the Green Lady murdered within its walls in the 15th century.",
    legend:
      "In 1477, Jacques de Brézé discovered his wife Charlotte of France in bed with her lover and murdered them both. Charlotte now wanders as La Dame Verte, a green apparition with hollow eye sockets and a gaping mouth where her face should be. She is most often seen at dawn in the tower room. The castle is still inhabited and open for overnight stays.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Battlefield of Culloden",
    slug: "battlefield-of-culloden",
    lat: 57.4769,
    lng: -4.0746,
    category: "BATTLEFIELD",
    country: "Scotland",
    city: "Inverness",
    description:
      "Site of the last pitched battle on British soil — 1,500 Highlanders slaughtered in under an hour on April 16, 1746.",
    legend:
      "Visitors report hearing battle sounds — swords clashing, men screaming — especially on the April 16 anniversary. A spectral Highlander in tartan has been seen kneeling among the clan graves. Dogs refuse to cross the moor. The NTS visitor centre staff regularly report hearing footsteps and whispers after closing time.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "5",
    name: "Poveglia Island",
    slug: "poveglia-island",
    lat: 45.3728,
    lng: 12.3261,
    category: "ASYLUM",
    country: "Italy",
    city: "Venice",
    description:
      "A plague quarantine island near Venice — 160,000 deaths, a psychiatric hospital, and now banned from public access.",
    legend:
      "Over 160,000 people died during the Black Death on this island. The soil is said to be 50% human ash. A psychiatric hospital built in 1922 was run by a doctor who performed experimental lobotomies. He reportedly went mad, threw himself from the bell tower, survived — then was strangled by a mist that rose from the ground. The Italian government permanently bans visitors.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "6",
    name: "Sedlec Ossuary",
    slug: "sedlec-ossuary",
    lat: 49.9974,
    lng: 15.2842,
    category: "CEMETERY",
    country: "Czech Republic",
    city: "Kutná Hora",
    description:
      "A chapel decorated entirely with the bones of 40,000 humans — chandeliers, coats of arms, garlands of skulls.",
    legend:
      "After holy soil from Jerusalem was sprinkled here in 1278, everyone wanted to be buried at Sedlec. The Black Death and Hussite Wars flooded the cemetery with 30,000 bodies. A half-blind monk began stacking the bones in 1511. In 1870, woodcarver František Rint arranged them into art. The bone chandelier contains at least one of every bone in the human body.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "7",
    name: "Leap Castle",
    slug: "leap-castle",
    lat: 52.9964,
    lng: -7.8997,
    category: "HAUNTED_HOUSE",
    country: "Ireland",
    city: "County Offaly",
    description:
      "Ireland's most haunted castle — built on an oubliette filled with impaled bones, haunted by 'It', a sheep-sized elemental.",
    legend:
      "In 1532, one O'Carroll brother murdered another — a priest — during mass. Workers later found an oubliette beneath a trapdoor: a pit spiked with wooden stakes, containing three cartloads of human bones. An elemental spirit called 'It' — the size of a sheep with a decomposed human face and the smell of rotting flesh — is the most feared presence. It has been seen by multiple independent witnesses.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "8",
    name: "Bhangarh Fort",
    slug: "bhangarh-fort",
    lat: 27.0944,
    lng: 76.2897,
    category: "CURSED_PLACE",
    country: "India",
    city: "Rajasthan",
    description:
      "A 17th-century fort so famously cursed that the Archaeological Survey of India prohibits entry after sunset.",
    legend:
      "A sorcerer named Singhia fell in love with the princess Ratnavati and enchanted her perfume oil to make her love him. She saw through the spell and smashed the bottle on a boulder, which rolled onto and crushed him. Dying, he cursed the entire city to ruin. The fort was abandoned overnight. Locals say anyone who enters after dark never returns. The ASI warning sign remains at the gate.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "9",
    name: "Tower of London",
    slug: "tower-of-london",
    lat: 51.5081,
    lng: -0.0759,
    category: "HAUNTED_HOUSE",
    country: "England",
    city: "London",
    description:
      "Nearly 1,000 years of imprisonment, torture and execution — and at least 13 documented apparitions still walking its halls.",
    legend:
      "Anne Boleyn's headless ghost is most frequently seen near the Tower Green where she was beheaded in 1536. A Yeoman Warder reported seeing her lead a ghostly procession through the Chapel Royal. Two young princes — Edward V and Richard, Duke of York — murdered in the Bloody Tower, have been seen as small shadowy figures holding hands. In 1817, a guard died of shock after encountering a ghost near the Crown Jewels room.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "10",
    name: "Catacombs of Paris",
    slug: "catacombs-of-paris",
    lat: 48.8338,
    lng: 2.3324,
    category: "CEMETERY",
    country: "France",
    city: "Paris",
    description:
      "300 km of tunnels beneath Paris containing the arranged bones of over 6 million people — the city's biggest secret.",
    legend:
      "The catacombs were created in 1786 to solve Paris's overflowing cemeteries. Bones were transferred at night in a procession of priests, then stacked in artistic formations. 'Cataphiles' illegally explore the forbidden tunnels regularly. In 1793, a man named Philibert Aspairt entered and was found dead 11 years later, his lantern still beside him. His grave is in the catacombs where he was found.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "11",
    name: "Pluckley Village",
    slug: "pluckley-village",
    lat: 51.1659,
    lng: 0.7337,
    category: "URBAN_LEGEND",
    country: "England",
    city: "Kent",
    description:
      "The most haunted village in England according to the Guinness Book of Records — 12 distinct ghosts documented.",
    legend:
      "Among the dozen ghosts: a highwayman impaled on a tree by a sword, a screaming man who fell into a claypipe at the brickworks, a Red Lady who wanders the churchyard searching for her lost baby, and a White Lady sealed in a tomb with a rose. The village is so famously haunted that paranormal investigators descend every Halloween, and locals report activity year-round.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "12",
    name: "Mary King's Close",
    slug: "mary-kings-close",
    lat: 55.9495,
    lng: -3.1915,
    category: "URBAN_LEGEND",
    country: "Scotland",
    city: "Edinburgh",
    description:
      "A network of sealed underground streets beneath Edinburgh's Royal Mile — entombed since the 17th century plague.",
    legend:
      "During the 1645 plague, entire families were walled into their homes to contain the outbreak. The streets were buried under a new building in 1753. The most famous ghost is Annie, a little girl whose doll is displayed in the 'Annie's Room' after a Japanese psychic reported feeling her crying there. Visitors still leave toys for her. The close was only opened to the public in 2003.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // ── Americas ─────────────────────────────────────────────────────────────
  {
    id: "13",
    name: "Waverly Hills Sanatorium",
    slug: "waverly-hills-sanatorium",
    lat: 38.1853,
    lng: -85.8658,
    category: "ASYLUM",
    country: "USA",
    city: "Louisville, Kentucky",
    description:
      "63,000 tuberculosis deaths between 1910–1961 — the body chute, shadow figures, and the suicide nurse of room 502.",
    legend:
      "The body chute — a 500-foot tunnel used to secretly remove corpses so surviving patients wouldn't lose hope — is considered one of the most haunted corridors in America. Shadow figures are reported in the hallways. Room 502's nurse, who hanged herself after discovering an unwanted pregnancy, is seen wandering the 5th floor. The hospital was so overwhelmed it used the tunnel to average 8 deaths per day at peak.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "14",
    name: "Island of the Dolls",
    slug: "island-of-the-dolls",
    lat: 19.2877,
    lng: -99.0987,
    category: "URBAN_LEGEND",
    country: "Mexico",
    city: "Mexico City",
    description:
      "Hundreds of mutilated, rotting dolls hang from trees on a small island — placed there over 50 years to appease a drowned girl.",
    legend:
      "Don Julian Santana Barrera found a drowned girl near the island in the 1950s and was tormented by her spirit. He hung dolls to appease her, spending 50 years collecting them, claiming to hear her whisper. In 2001, he was found drowned in the exact same spot as the girl. Visitors report the dolls' eyes follow them and whisper after dark. His family now runs tours — and says he still wanders the island at night.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "15",
    name: "The Stanley Hotel",
    slug: "the-stanley-hotel",
    lat: 40.3772,
    lng: -105.5217,
    category: "HAUNTED_HOUSE",
    country: "USA",
    city: "Estes Park, Colorado",
    description:
      "The hotel that inspired Stephen King's The Shining — where King stayed in room 217 and dreamed the entire novel.",
    legend:
      "Stephen King checked into room 217 in 1974 and had a nightmare about his son being chased through the corridors. He woke, wrote the premise, and The Shining was born. The hotel's founder F.O. Stanley is still seen in the billiard room. Children are heard playing in the ballroom at night — but the ballroom is always empty. Room 217 is the most requested room in the hotel.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "16",
    name: "Winchester Mystery House",
    slug: "winchester-mystery-house",
    lat: 37.3184,
    lng: -121.9511,
    category: "HAUNTED_HOUSE",
    country: "USA",
    city: "San Jose, California",
    description:
      "A Victorian mansion built continuously for 38 years with staircases to nowhere, doors opening onto walls, and 160 rooms.",
    legend:
      "Sarah Winchester, widow of the rifle manufacturer, was told by a medium that she must build continuously to confuse the spirits of those killed by Winchester rifles. She built 24 hours a day from 1884 until her death in 1922 — 38 years, $5.5 million, 160 rooms. Staircases lead into ceilings. Doors open onto 10-foot drops. She slept in a different room each night to confuse the ghosts.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "17",
    name: "Cemetery of Dissenters — Recoleta",
    slug: "recoleta-cemetery",
    lat: -34.5872,
    lng: -58.3931,
    category: "CEMETERY",
    country: "Argentina",
    city: "Buenos Aires",
    description:
      "A city of the dead in the heart of Buenos Aires — 4,800 vaults, labyrinthine alleys, and Evita's tomb.",
    legend:
      "The cemetery is a city unto itself — with streets, avenues, and neighborhoods of marble mausoleums. Rufina Cambaceres was buried alive here in 1902; she woke in her coffin, clawed the lid, and died of shock before anyone came. Her ghost is seen wandering the alleys at night. A black cat said to be the spirit of a caretaker has been photographed inside sealed vaults.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "18",
    name: "Poveglia of the New World — Eastern State Penitentiary",
    slug: "eastern-state-penitentiary",
    lat: 39.9681,
    lng: -75.1724,
    category: "ASYLUM",
    country: "USA",
    city: "Philadelphia, Pennsylvania",
    description:
      "The world's most expensive building when built in 1829 — a prison so brutal that Al Capone reportedly fled its ghosts.",
    legend:
      "Eastern State introduced solitary confinement to America. Prisoners were hooded whenever outside their cells, forbidden to speak, and kept in total darkness. Al Capone's cell was luxurious — but he reportedly begged to be moved, claiming the ghost of Jimmy Clark, a victim of the St. Valentine's Day Massacre, haunted him there. Guards still report shadowy figures and cackling laughs in the cellblocks.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // ── Asia ─────────────────────────────────────────────────────────────────
  {
    id: "19",
    name: "Aokigahara Forest",
    slug: "aokigahara-forest",
    lat: 35.4722,
    lng: 138.7611,
    category: "CURSED_PLACE",
    country: "Japan",
    city: "Fujikawaguchiko",
    description:
      "Japan's Sea of Trees at the base of Mount Fuji — silent, compass-breaking, and infamous as the world's most visited suicide site.",
    legend:
      "The volcanic rock blocks compass needles and absorbs sound, creating a total, unnatural silence. Yurei (angry spirits) are said to pull the living deeper into the trees. Ribbons of plastic tape left by those who entered and never returned still wind between the trunks. Authorities stopped publishing the annual body count to discourage visits. Forestry workers report hearing weeping from deep in the woods.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "20",
    name: "Fengdu Ghost City",
    slug: "fengdu-ghost-city",
    lat: 29.8589,
    lng: 107.7292,
    category: "URBAN_LEGEND",
    country: "China",
    city: "Chongqing",
    description:
      "An ancient city built entirely for the dead — temples, statues and infrastructure for the underworld, used for 2,000 years.",
    legend:
      "Fengdu was established as a place to practice for death. Statues of demons torture the wicked, while the righteous pass tests to enter paradise. To test your virtue, you must cross the Bridge of Helplessness in 3 steps, stand on the 'Ghost Torturing Pass' for 3 minutes, and look in the Mirror of Sinners without seeing a demon. Those who fail the tests are said to be dragged below.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "21",
    name: "Changi Beach",
    slug: "changi-beach",
    lat: 1.3875,
    lng: 103.9872,
    category: "BATTLEFIELD",
    country: "Singapore",
    city: "Changi",
    description:
      "A seemingly peaceful beach where thousands of Chinese civilians were massacred by Japanese forces in 1942.",
    legend:
      "During Operation Sook Ching, Japanese forces systematically executed an estimated 25,000–50,000 Chinese Singaporeans. Changi Beach was one of the primary massacre sites — mass graves were found after the war. Locals report hearing screaming from the beach at night, seeing headless figures wading in the water, and encountering men in wartime clothing who vanish when approached. The screaming is said to peak on moonless nights.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "22",
    name: "Hashima Island",
    slug: "hashima-island",
    lat: 32.6279,
    lng: 129.7384,
    category: "CURSED_PLACE",
    country: "Japan",
    city: "Nagasaki",
    description:
      "Battleship Island — a fully intact abandoned city visible from the mainland, frozen in 1974 when its 5,000 residents fled overnight.",
    legend:
      "Hashima was a forced labour camp during WWII where Korean and Chinese workers were worked to death in the underwater coal mines. After the war it became a dense company town; in 1974 Mitsubishi closed the mine and all 5,259 residents left within weeks. Buildings, furniture, and personal belongings remain exactly as they were left. Former forced labourers' descendants say the island is dense with restless spirits who died in the mines below.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // ── Africa & Middle East ─────────────────────────────────────────────────
  {
    id: "23",
    name: "Mummies of Palermo Catacombs",
    slug: "palermo-catacombs",
    lat: 38.1117,
    lng: 13.3317,
    category: "CEMETERY",
    country: "Italy",
    city: "Palermo",
    description:
      "8,000 mummies line the walls of underground corridors — fully dressed, posing in the clothes they wore in life.",
    legend:
      "Capuchin monks began mummifying their dead in 1599. For 300 years, wealthy Palermitans paid to have their bodies displayed here. The most disturbing resident is Rosalia Lombardo, a 2-year-old who died in 1920 — so perfectly preserved she appears to be sleeping. Scientists have noticed her eyes open and close periodically throughout the day. Her father commissioned the mummification because he could not bear to bury her.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "24",
    name: "Deception Island",
    slug: "deception-island",
    lat: -62.9728,
    lng: -60.6517,
    category: "CURSED_PLACE",
    country: "Antarctica",
    city: "South Shetland Islands",
    description:
      "An active volcano shaped like a broken ring — ships sail inside a caldera past a whale bone cemetery and an abandoned research station.",
    legend:
      "Whalers used the island's caldera as a natural harbour from the 1800s, boiling whale carcasses in the volcanic water. The beach is covered in whale bones and rusting iron boilers. An Argentine research station was destroyed by volcanic eruptions in 1967 and 1969 and never rebuilt — its ruins remain in the ash. Sailors say the island lures ships inside the caldera and then seals the entrance with fog.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // ── Eastern Europe ────────────────────────────────────────────────────────
  {
    id: "25",
    name: "Chernobyl Exclusion Zone",
    slug: "chernobyl-exclusion-zone",
    lat: 51.3890,
    lng: 30.0993,
    category: "CURSED_PLACE",
    country: "Ukraine",
    city: "Pripyat",
    description:
      "A 2,600 km² zone frozen in 1986 — the ghost city of Pripyat, the reactor, and a kindergarten with toys still on the floor.",
    legend:
      "Pripyat was evacuated in 36 hours; residents were told to bring food for 3 days and never returned. Apartments still hold family photos, children's drawings, and half-eaten meals. The amusement park's Ferris wheel was completed but never operated — it opened for exactly one day, April 27, 1986, the day of evacuation. Workers in the zone report a shadow figure near Reactor 4 they call 'the Wormwood Angel', seen before equipment failures.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "26",
    name: "Oradour-sur-Glane",
    slug: "oradour-sur-glane",
    lat: 45.9318,
    lng: 1.0337,
    category: "BATTLEFIELD",
    country: "France",
    city: "Haute-Vienne",
    description:
      "A French village massacred by the SS in 1944 and preserved forever as a ruin — no one was ever allowed to rebuild.",
    legend:
      "On June 10, 1944, the 2nd SS Panzer Division Das Reich herded all 642 inhabitants into the church and barns and burned them alive. The village was left exactly as it was — rusted cars on the streets, sewing machines in kitchens, a child's tricycle in a yard. President de Gaulle declared it a permanent memorial. Visitors report hearing children playing and the smell of smoke when the village is empty.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "27",
    name: "Byberry Mental Asylum",
    slug: "byberry-mental-asylum",
    lat: 40.0918,
    lng: -75.0299,
    category: "ASYLUM",
    country: "USA",
    city: "Philadelphia, Pennsylvania",
    description:
      "A psychiatric hospital so horrifically abusive it was called a 'concentration camp' — shut down in 1990, demolished in 2006.",
    legend:
      "At its peak, Byberry housed 6,000 patients in facilities built for 1,000. A 1946 expose described patients naked, caged, and lying in their own waste. Staff assaulted patients routinely. When it closed, hundreds of patients were simply released onto the streets with $25 and a bus ticket. Urban explorers who entered before demolition described unexplained voices, doors slamming, and being physically pushed.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "28",
    name: "Kuldhara Village",
    slug: "kuldhara-village",
    lat: 26.8721,
    lng: 70.5613,
    category: "CURSED_PLACE",
    country: "India",
    city: "Jaisalmer, Rajasthan",
    description:
      "An entire village abandoned overnight in 1825 by 1,500 people — who cursed it so no one could ever live there again.",
    legend:
      "The Paliwal Brahmin clan abandoned Kuldhara in a single night to escape the tyrannical minister Salim Singh, who demanded the village chief's daughter. Before leaving, the villagers cursed the land so it could never be inhabited again. The ruins stand exactly as left. The Rajasthan government officially classifies the area as haunted. Travellers who camp overnight report being chased from the ruins by unseen forces before dawn.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "29",
    name: "Centralia, Pennsylvania",
    slug: "centralia-pennsylvania",
    lat: 40.8032,
    lng: -76.3413,
    category: "CURSED_PLACE",
    country: "USA",
    city: "Columbia County, Pennsylvania",
    description:
      "A town with an underground coal fire burning since 1962 — smoke still rises from cracks in the road, and only 5 residents remain.",
    legend:
      "A coal mine fire ignited beneath Centralia in 1962 and has never been extinguished. The ground is warm to the touch. Steam and carbon monoxide vent from cracks in roads and yards. The town was condemned in 1992; nearly all 1,000 residents relocated. Five holdouts refuse to leave. The abandoned roads with steam rising from fissures inspired the Silent Hill video game and film. The fire is projected to burn for another 250 years.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  // ── Europe cont. ─────────────────────────────────────────────────────────
  {
    id: "31",
    name: "Screaming Tunnel",
    slug: "screaming-tunnel-niagara",
    lat: 43.0896,
    lng: -79.0849,
    category: "URBAN_LEGEND",
    country: "Canada",
    city: "Niagara Falls, Ontario",
    description: "A 19th-century railway tunnel where lighting a match at midnight is said to summon a screaming ghost.",
    legend: "The tunnel was built in the 1870s beneath the Grand Trunk Railway. Legend says a farmhouse nearby burned down; a girl on fire ran into the tunnel and died there. If you light a match at midnight in the tunnel, the flame will be extinguished by an unseen force and a scream will echo from the walls. The tunnel was featured in David Cronenberg's 1983 film The Dead Zone.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "32",
    name: "Hellfire Club",
    slug: "hellfire-club-dublin",
    lat: 53.2697,
    lng: -6.3472,
    category: "HAUNTED_HOUSE",
    country: "Ireland",
    city: "Dublin",
    description: "A ruined hunting lodge on a Dublin mountaintop where 18th-century aristocrats held Satanic rituals.",
    legend: "Built in 1725 by William Conolly, the lodge was used by the Hellfire Club — a group of wealthy Irish rakes rumoured to practice black magic and devil worship. One night a card game was interrupted when a card fell under the table; a player reaching for it saw that a stranger's foot was a cloven hoof. The stranger — the Devil — vanished in a ball of fire. A large black cat haunts the ruins.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "33",
    name: "Borgvattnet Vicarage",
    slug: "borgvattnet-vicarage",
    lat: 63.4333,
    lng: 16.0667,
    category: "HAUNTED_HOUSE",
    country: "Sweden",
    city: "Borgvattnet",
    description: "Sweden's most haunted house — so frightening that anyone who spends the night receives a certificate of bravery.",
    legend: "The haunting began in 1927 when chaplain Nils Hedlund reported seeing laundry torn from the line by unseen hands. Since then, a rotating cast of ghosts has been documented: an old woman in grey, three women sitting by the fireplace, a weeping figure, and a rocking chair that rocks on its own. The vicarage now operates as a guest house — guests who survive the night receive a printed certificate.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "34",
    name: "Château de Brézé",
    slug: "chateau-de-breze",
    lat: 47.1733,
    lng: -0.1742,
    category: "HAUNTED_HOUSE",
    country: "France",
    city: "Brézé",
    description: "A Loire Valley château with the deepest dry moat in Europe — and an underground city carved into the rock below.",
    legend: "The troglodyte village beneath the castle was carved over centuries and contains stables, a bakery, a winery, and living quarters. In the 16th century, a woman was walled alive in one of the underground chambers for adultery. Her scratches can still be seen on the stone. Staff report candles relighting themselves and the smell of bread baking in the underground bakery that has been cold for 200 years.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "35",
    name: "Belchite",
    slug: "belchite",
    lat: 41.3031,
    lng: -0.7564,
    category: "BATTLEFIELD",
    country: "Spain",
    city: "Zaragoza",
    description: "A Spanish Civil War ghost town left in ruins since 1937 by Franco's order — as a monument to Republican destruction.",
    legend: "In 1937, Belchite was the site of a brutal two-week battle. Franco ordered the ruins never to be cleared — a new town was built beside them. The shattered church, bombed streets, and collapsed houses remain exactly as the battle left them. Locals hear voices and weeping from the ruins at night. Paranormal investigators consistently report extreme EMF readings near the church bell tower.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "36",
    name: "Moosham Castle",
    slug: "moosham-castle",
    lat: 47.2833,
    lng: 13.5833,
    category: "HAUNTED_HOUSE",
    country: "Austria",
    city: "Unternberg",
    description: "The 'Witch's Castle' — site of over 100 torture-executions during the Salzburg witch trials of the 1670s.",
    legend: "Between 1675 and 1690, over 100 people — mostly beggars and shepherds — were tortured and executed at Moosham on charges of witchcraft. In the 19th century, deer and cattle were found inexplicably slaughtered near the castle — unskinned and bloodless. A werewolf curse was declared. The Count had several people executed for lycanthropy. The castle is still owned by the same family and reports of ghostly figures continue.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "37",
    name: "Beelitz-Heilstätten",
    slug: "beelitz-heilstatten",
    lat: 52.2167,
    lng: 12.9167,
    category: "ASYLUM",
    country: "Germany",
    city: "Beelitz, Brandenburg",
    description: "A vast abandoned sanatorium complex where Hitler recovered from a WWI wound — later a Soviet military hospital until 1994.",
    legend: "The complex treated thousands of tuberculosis patients from 1898. Hitler was treated here in 1916 after being wounded at the Somme. The Soviets occupied it after WWII and kept it sealed for 50 years; when they left in 1994, they took nothing — medical equipment, surgical tools, patient records, and beds remain exactly as left. Urban explorers report being followed by a presence in the surgical wing.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "38",
    name: "Château de Montségur",
    slug: "chateau-de-montsegur",
    lat: 42.8756,
    lng: 1.8317,
    category: "BATTLEFIELD",
    country: "France",
    city: "Ariège",
    description: "A mountain fortress where 200 Cathar heretics were burned alive in 1244 — their ashes never fully cooled, locals say.",
    legend: "In 1244, after a 9-month siege, 207 Cathars descended from the fortress, refused to recant their faith, and walked into a mass pyre. Witnesses reported they sang as they burned. On the anniversary, March 16th, a strange perfumed scent rises from the field below the castle. The Cathars are said to have hidden the Holy Grail here before the siege — and treasure hunters still dig.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "39",
    name: "Dargavs — City of the Dead",
    slug: "dargavs-city-of-the-dead",
    lat: 42.8333,
    lng: 44.3167,
    category: "CEMETERY",
    country: "Russia",
    city: "North Ossetia",
    description: "A remote Caucasian valley filled with medieval stone crypts containing the mummified remains of entire families.",
    legend: "When plague swept through North Ossetia in the 17th century, families climbed into their ancestral crypts with a week's supply of food and water and sealed themselves inside to die, so as not to infect others. The crypts remain sealed — many still contain mummies in their original burial clothes, preserved by the dry mountain air. The valley is so remote that locals still say 'those who go do not return.'",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "40",
    name: "Stull Cemetery",
    slug: "stull-cemetery",
    lat: 38.9319,
    lng: -95.5311,
    category: "CEMETERY",
    country: "USA",
    city: "Stull, Kansas",
    description: "A rural Kansas cemetery claimed by legend to be one of the seven gateways to Hell on Earth.",
    legend: "The legend says the Devil himself visits Stull Cemetery twice a year — Halloween and the Spring Equinox. The ruins of an old church here are said to contain a staircase descending into Hell. Rain reportedly never falls inside the ruins even in a downpour. Pope John Paul II allegedly rerouted his 1995 papal flight to avoid flying over the site. The church was demolished in 2002 — but the legend persists.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // ── Americas cont. ────────────────────────────────────────────────────────
  {
    id: "41",
    name: "The Myrtles Plantation",
    slug: "myrtles-plantation",
    lat: 30.7938,
    lng: -91.1762,
    category: "HAUNTED_HOUSE",
    country: "USA",
    city: "St. Francisville, Louisiana",
    description: "An antebellum plantation built on a Tunica burial ground — site of at least 10 murders and a famous ghost in a green turban.",
    legend: "The most famous ghost is Chloe, an enslaved woman who baked a poisoned oleander cake that killed the plantation owner's wife and two daughters. She was hanged by other enslaved people and thrown in the bayou. She appears wearing a green turban to cover the ear cut off as punishment for eavesdropping. The plantation's mirror is said to contain the handprints of the murdered children.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "42",
    name: "Trans-Allegheny Lunatic Asylum",
    slug: "trans-allegheny-lunatic-asylum",
    lat: 39.2756,
    lng: -80.3434,
    category: "ASYLUM",
    country: "USA",
    city: "Weston, West Virginia",
    description: "The largest hand-cut stone building in North America — designed for 250 patients, it housed 2,400 at its peak.",
    legend: "At its overcrowded height in the 1950s, patients were crammed four to a cell designed for one. Lobotomies, electroshock, and hydrotherapy were routine. Ward 2 — the Civil War ward — is considered the most active, with shadow figures and disembodied screaming. The ghost of a Civil War soldier who died in the building before it was even finished is the most frequently encountered presence.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "43",
    name: "USS Hornet",
    slug: "uss-hornet",
    lat: 37.7729,
    lng: -122.3003,
    category: "HAUNTED_HOUSE",
    country: "USA",
    city: "Alameda, California",
    description: "An aircraft carrier with 300 deaths on board — now a museum where crew members still report seeing ghostly sailors.",
    legend: "The USS Hornet had the highest suicide rate of any US Navy ship — over 300 men died aboard during its service. Museum staff report seeing apparitions in Navy uniforms in the engine room and hangar bay. Overnight ghost hunts regularly capture unexplained voices. The ghost of one sailor reportedly tells visitors 'this is MY ship' and shoves them. The captain's sea cabin is considered the most active spot.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "44",
    name: "Château Frontenac Catacombs",
    slug: "chateau-frontenac-catacombs",
    lat: 46.8199,
    lng: -71.2046,
    category: "CEMETERY",
    country: "Canada",
    city: "Quebec City",
    description: "Beneath old Quebec City lies a network of tunnels connecting buildings — originally used to move bodies during siege warfare.",
    legend: "Quebec City was besieged multiple times; the tunnels allowed defenders to move troops and supplies without exposure. Mass graves from the 1832 cholera epidemic were discovered beneath the streets. The Plains of Abraham above the city saw 15 minutes of battle in 1759 that decided the fate of North America — and the screaming of soldiers is still heard there on foggy nights.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "45",
    name: "Poveglia's Twin — Alcatraz Island",
    slug: "alcatraz-island",
    lat: 37.8267,
    lng: -122.4230,
    category: "ASYLUM",
    country: "USA",
    city: "San Francisco, California",
    description: "America's most notorious federal penitentiary, home to Al Capone — and reportedly still home to the spirits of its most violent inmates.",
    legend: "Cell 14D — the isolation cell — is reported to be inexplicably cold even on warm days. Guards during the active years reported hearing crying and moaning from it. In 1946, a prisoner screaming that he was being strangled by 'a creature with glowing eyes' was found dead the next morning with no explanation. Ranger staff report being touched and hearing voices long after the last tourist has left.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "46",
    name: "Manchac Swamp",
    slug: "manchac-swamp",
    lat: 30.2502,
    lng: -90.4162,
    category: "CURSED_PLACE",
    country: "USA",
    city: "Louisiana",
    description: "The 'Haunted Swamp' of Louisiana — cursed by a voodoo priestess in 1915, wiped out by a hurricane the same year.",
    legend: "Julia Brown, a local traiteur (faith healer), sang at her own funeral: 'One day I'm gonna die and take the whole town with me.' She died in 1915 — the same day a hurricane hit, wiping out the entire surrounding community. Their graves remain in the swamp, partially underwater. Pirogue drivers report a wailing woman walking on water and a ghostly steamboat that appears and disappears in the cypress trees.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "47",
    name: "Villisca Axe Murder House",
    slug: "villisca-axe-murder-house",
    lat: 40.9297,
    lng: -94.9752,
    category: "HAUNTED_HOUSE",
    country: "USA",
    city: "Villisca, Iowa",
    description: "The site of an unsolved 1912 mass murder where eight people were killed in their sleep — the case was never solved.",
    legend: "On June 10, 1912, Josiah Moore, his wife, four children, and two visiting girls were found bludgeoned to death with an axe. All mirrors were covered; a piece of bacon was found beside the axe. Over 100 suspects were investigated; no one was ever convicted. The house has been restored to its 1912 state. Overnight guests report children's voices, moving objects, and the sensation of being watched from the ceiling.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "48",
    name: "Rose Hall Great House",
    slug: "rose-hall-great-house",
    lat: 18.4833,
    lng: -77.8167,
    category: "HAUNTED_HOUSE",
    country: "Jamaica",
    city: "Montego Bay",
    description: "An 18th-century plantation great house haunted by the White Witch of Rose Hall — said to have killed three husbands.",
    legend: "Annie Palmer arrived in Jamaica in 1820, learned voodoo from a Haitian nanny, and became the plantation's mistress. She is said to have murdered three husbands by poisoning, stabbing, and strangling. She tortured enslaved people for entertainment and took enslaved men as lovers, then had them killed. She was eventually murdered by one such man. Her ghost — the White Witch — is seen riding a white horse through the cane fields at midnight.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // ── Asia cont. ────────────────────────────────────────────────────────────
  {
    id: "49",
    name: "Chaonei No. 81",
    slug: "chaonei-no-81",
    lat: 39.9267,
    lng: 116.4264,
    category: "HAUNTED_HOUSE",
    country: "China",
    city: "Beijing",
    description: "Beijing's most famous haunted house — a French Catholic mission building where a bride was sealed inside during a collapse.",
    legend: "Built in 1900 by French Catholics, the building was abandoned when the Communists came to power in 1949. Legend says a Nationalist official's wife refused to leave as the People's Liberation Army advanced — she was sealed in the building when it was abandoned and her screams could be heard for years. Passers-by have heard piano music, seen lights moving, and reported being called by name from the empty windows.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "50",
    name: "Old Changi Hospital",
    slug: "old-changi-hospital",
    lat: 1.3847,
    lng: 103.9892,
    category: "ASYLUM",
    country: "Singapore",
    city: "Changi",
    description: "A WWII-era hospital used by the Japanese Kempeitai (secret police) for interrogation and torture.",
    legend: "During the Japanese occupation of Singapore (1942–45), the Kempeitai used this hospital complex to torture and execute prisoners of war and civilians. Their screams are said to have been heard throughout Changi. After independence, the hospital was used until 1997, when staff refused to work night shifts due to apparitions of headless Japanese soldiers, crying children, and a ghost in a bloodstained nurse's uniform in the operating theatre.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "51",
    name: "Wat Mahathat — Headless Buddha",
    slug: "wat-mahathat-headless",
    lat: 14.3592,
    lng: 100.5697,
    category: "URBAN_LEGEND",
    country: "Thailand",
    city: "Ayutthaya",
    description: "The ruins of a 14th-century capital — 400 headless Buddha statues, their heads sold to Western collectors in the 1800s.",
    legend: "When Burmese armies sacked Ayutthaya in 1767, they decapitated every Buddha statue they could reach. Later, Western collectors and looters removed hundreds more. Local belief holds that Buddha statues retain spiritual power — that the severed heads cry out at night from wherever they were taken, trying to find their bodies. The tree-root Buddha head of Wat Mahathat — grown into a fig tree's roots — is said to grant wishes but curse those who photograph it irreverently.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "52",
    name: "Clark Air Base Hospital",
    slug: "clark-air-base-hospital",
    lat: 15.1784,
    lng: 120.5574,
    category: "ASYLUM",
    country: "Philippines",
    city: "Angeles City",
    description: "An abandoned US Air Force hospital left frozen in time after the 1991 Mount Pinatubo eruption — with patient charts still in the rooms.",
    legend: "When Pinatubo erupted in June 1991, the base was evacuated in hours. The hospital was left mid-operation — charts in filing cabinets, equipment on shelves, surgical tools still laid out. Looters removed the metal, but rooms and corridors remain ash-covered and intact. Local Aeta people who lived near the mountain say the eruption was caused by angry spirits disturbed by the base's construction, and that the hospital traps the souls of those who died there.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "53",
    name: "Lawang Sewu",
    slug: "lawang-sewu",
    lat: -6.9842,
    lng: 110.4089,
    category: "ASYLUM",
    country: "Indonesia",
    city: "Semarang",
    description: "A Dutch colonial building known as the Thousand Doors — used by the Japanese as a prison and execution site in WWII.",
    legend: "Built in 1904 as the Dutch East Indies Railway HQ, Lawang Sewu was seized by the Japanese in 1942 and its basement used as a prison where hundreds died. During the Indonesian National Revolution in 1945, a savage three-day battle was fought in the building. The basement is permanently flooded — local legend says the water is stained with the blood of the dead. The headless ghost of a Dutch woman is the most frequently reported apparition.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "54",
    name: "Himuro Mansion",
    slug: "himuro-mansion",
    lat: 35.7719,
    lng: 139.5464,
    category: "HAUNTED_HOUSE",
    country: "Japan",
    city: "Tokyo",
    description: "The inspiration for the Fatal Frame video game series — a mansion where a ritual murder of an entire family was performed to seal a gate to Hell.",
    legend: "The mansion was the site of a ritual called the 'Strangling Ritual' in which a young girl was tied to ropes attached to five ox-pulled carts that then drove in opposite directions, tearing her apart to seal a gate between worlds. When the ritual failed in one generation, the master of the house killed the entire family. The bodies were found frozen, their faces distorted in terror. Whether the house truly exists is debated — which perhaps makes it more disturbing.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "55",
    name: "Bhangarh Fort — Ajabgarh",
    slug: "ajabgarh",
    lat: 27.1049,
    lng: 76.2897,
    category: "CURSED_PLACE",
    country: "India",
    city: "Rajasthan",
    description: "A ghost town beside Bhangarh abandoned simultaneously — residents fled overnight and never returned.",
    legend: "Ajabgarh was abandoned at the same time as Bhangarh, apparently due to the same curse. Unlike Bhangarh it receives no tourists and no government signage. Locals say the two towns are connected by an underground tunnel used by the cursed spirits. The ruins are completely overtaken by vegetation. A shepherd who grazed his flock there reported the animals refused to enter and one goat that did was found dead, twisted as if wrung like a cloth.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "56",
    name: "Agrasen Ki Baoli",
    slug: "agrasen-ki-baoli",
    lat: 28.6267,
    lng: 77.2203,
    category: "CURSED_PLACE",
    country: "India",
    city: "New Delhi",
    description: "A 60-step stepwell in the heart of Delhi — its black water is said to hypnotically draw visitors to drown themselves.",
    legend: "The stepwell dates to the 14th century and descends 60 steps into black, still water. The water appears black due to algae but locals maintain it is the colour of the evil beneath. Visitors report an irresistible compulsion to keep walking down toward the water. Several drownings have occurred over the years with no apparent reason — the victims simply walked in. The stepwell is supposedly built on the ruins of a temple of a dark goddess.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "57",
    name: "Nan Madol",
    slug: "nan-madol",
    lat: 6.8447,
    lng: 158.3328,
    category: "URBAN_LEGEND",
    country: "Micronesia",
    city: "Pohnpei",
    description: "A lost city of 100 artificial islands in the Pacific — built without metal tools, the origin of its megaliths remains unknown.",
    legend: "Nan Madol was built between 1200–1500 CE by the Saudeleur dynasty using basalt columns weighing up to 50 tons each. No one knows how they were moved across open ocean. Local legend says twin sorcerers Olisihpa and Olosohpa used magic to float the stones through the air. The city is only accessible by boat at high tide and locals refuse to go there at night, believing the spirits of the Saudeleur kings — who were tyrants — still rule the ruins.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // ── Africa & Middle East cont. ────────────────────────────────────────────
  {
    id: "58",
    name: "Great Zimbabwe Ruins",
    slug: "great-zimbabwe",
    lat: -20.2667,
    lng: 30.9333,
    category: "URBAN_LEGEND",
    country: "Zimbabwe",
    city: "Masvingo",
    description: "A medieval African city of 18,000 people — abandoned overnight around 1450, the reason still unknown.",
    legend: "Great Zimbabwe was the capital of the Kingdom of Zimbabwe and housed 18,000 people. Around 1450, the entire city was abandoned with no evidence of invasion, disease, or famine. The inhabitants vanished. Colonial rulers denied the city's African origin, claiming it was built by Phoenicians or lost Israelites — an erasure that persists in local memory as its own kind of haunting. The stone bird-totems taken by colonists continue to cause diplomatic disputes.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "59",
    name: "Deir el-Medina",
    slug: "deir-el-medina",
    lat: 25.7308,
    lng: 32.6006,
    category: "CEMETERY",
    country: "Egypt",
    city: "Luxor",
    description: "The village of the workers who built the Valley of the Kings — their tombs contain the world's first documented labour strike.",
    legend: "The workers of Deir el-Medina built the royal tombs for 400 years, from 1550–1080 BCE. In 1170 BCE they went on strike — the first recorded in history — when the pharaoh stopped paying their grain wages. Their own tombs are extraordinarily elaborate. They kept administrative records documenting who was absent and why: 'ill', 'offering to his god', or the cryptic notation 'with the women' on certain days of the month, believed to mean menstruation.",
    spookyScore: 2,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "60",
    name: "Kolmanskop",
    slug: "kolmanskop",
    lat: -26.7069,
    lng: 15.2303,
    category: "CURSED_PLACE",
    country: "Namibia",
    city: "Lüderitz",
    description: "A diamond-rush ghost town in the Namib Desert, being slowly swallowed by sand dunes — its ballroom still has a piano.",
    legend: "Founded by German colonists in 1908 after a worker found a diamond, Kolmanskop grew into a lavish town with a ballroom, theatre, skittle alley, and x-ray machine. When richer diamond fields were found to the south in 1928, everyone left. The sand moved in immediately. The hospital still has operating tables, the ballroom still has a piano, and sand dunes push through every window. Former residents' descendants have reported seeing apparitions in the shifting sand.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "61",
    name: "House of Slaves — Gorée Island",
    slug: "goree-island",
    lat: 14.6680,
    lng: -17.3972,
    category: "BATTLEFIELD",
    country: "Senegal",
    city: "Dakar",
    description: "An island slave-trading post with the famous 'Door of No Return' — the last sight of Africa for millions.",
    legend: "Gorée Island was used as a slave-trading post from the 15th to 19th centuries. The House of Slaves contains cells where men, women, and children were kept before being loaded onto ships. The 'Door of No Return' opens directly onto the ocean — there was no dock, just the sea. Visitors report an overwhelming feeling of grief and a physical heaviness in the cells. The ocean is visible through the door still, unchanged since the last ship departed.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "62",
    name: "Palmyra Atoll",
    slug: "palmyra-atoll",
    lat: 5.8833,
    lng: -162.0833,
    category: "CURSED_PLACE",
    country: "USA",
    city: "Pacific Ocean",
    description: "A remote Pacific atoll with a history of shipwrecks, murders, and disappearances — and a rumoured curse on all who stay.",
    legend: "In 1974, a couple sailing to Palmyra vanished. Their partially burned boat was later found — and the partial remains of the woman in a metal container. The man was never found. The case was never solved. WWII sailors stationed there reported extreme psychological disturbances, unexplained lights, and boats disappearing at anchor. The atoll is currently a nature refuge, but every caretaker who has stayed more than a few months has reported nightmares, paranoia, and a compulsion to leave.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // ── More Americas ─────────────────────────────────────────────────────────
  {
    id: "63",
    name: "Gettysburg Battlefield",
    slug: "gettysburg-battlefield",
    lat: 39.8119,
    lng: -77.2252,
    category: "BATTLEFIELD",
    country: "USA",
    city: "Gettysburg, Pennsylvania",
    description: "The bloodiest battle of the Civil War — 51,000 casualties in 3 days, more dead per acre than almost anywhere in America.",
    legend: "Pickett's Charge on July 3, 1863 sent 12,500 Confederate soldiers across an open field into Union guns. Over half were killed or wounded in 50 minutes. The battlefield ghost industry began in 1863 — soldiers were burying their comrades when they reported seeing the dead rise and walk. The misty apparitions of Confederate soldiers have been photographed during re-enactments. Camera anomalies, unexplained voices, and the smell of gunpowder with no source are routine.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "64",
    name: "Coyote Lake — Zona del Silencio",
    slug: "zona-del-silencio",
    lat: 26.6833,
    lng: -103.8167,
    category: "CURSED_PLACE",
    country: "Mexico",
    city: "Durango/Chihuahua border",
    description: "The Zone of Silence — a desert where radio waves don't work, compasses spin, and meteorites fall at an anomalous rate.",
    legend: "In 1970, an Athena missile fired from White Sands, New Mexico, malfunctioned and crashed in this desert. The US military set up a secret base to recover it. The zone sits at the same latitude as the Bermuda Triangle and the Egyptian pyramids. Radio signals are absorbed, television and radio don't function, compasses behave erratically, and the area receives more meteorite impacts per square kilometer than almost anywhere else on Earth. Blond-haired strangers who speak perfect Spanish are occasionally encountered and then vanish.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "65",
    name: "Overtoun of the Americas — Suicide Forest of Aokigahara",
    slug: "hell-hollow-new-york",
    lat: 41.9184,
    lng: -73.9985,
    category: "CURSED_PLACE",
    country: "USA",
    city: "Hudson Valley, New York",
    description: "A Hudson Valley hollow where animals and people have reported sudden overwhelming dread and a compulsion to flee.",
    legend: "The hollow near the abandoned town of Whaley has been associated with supernatural fear since Dutch colonial times. The Lenape people avoided it, calling it 'the place of the bad spirit'. Farmers who tried to build there reported livestock dying without cause, an unshakeable feeling of being watched, and nightmares of being buried alive. The area around it shows anomalous magnetic readings that no geological survey has explained.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "66",
    name: "Bobby Mackey's Music World",
    slug: "bobby-mackeys-music-world",
    lat: 39.0700,
    lng: -84.4780,
    category: "HAUNTED_HOUSE",
    country: "USA",
    city: "Wilder, Kentucky",
    description: "A country music nightclub built on a former slaughterhouse — where a well in the basement is said to be a portal to Hell.",
    legend: "The building was a slaughterhouse in the 1800s; blood drained into a well in the basement. In 1896, a Satanic cult used the well for rituals and decapitated a woman, tossing her head in. The well was later covered with concrete. In 1978, a caretaker was possessed and attacked his wife in the club. The current owner Bobby Mackey himself was allegedly possessed on stage. A warning sign at the entrance cautions visitors about supernatural activity.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "67",
    name: "Catacombs of Lima",
    slug: "catacombs-of-lima",
    lat: -12.0451,
    lng: -77.0296,
    category: "CEMETERY",
    country: "Peru",
    city: "Lima",
    description: "A labyrinth of tunnels beneath Lima's historic centre containing the bones of 70,000 people — organized by disease and social class.",
    legend: "The catacombs beneath the Basilica and Convent of San Francisco served as Lima's main cemetery from the 16th century until 1821. The bones of 70,000 people are arranged in geometric patterns in circular bone wells — femurs around the edge, skulls in the centre, vertebrae in spirals. A tunnel is said to connect to the Presidential Palace. Workers who disturb the bone patterns report objects moving in their homes that night.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "68",
    name: "Mound Cemetery — Chillicothe",
    slug: "mound-cemetery-chillicothe",
    lat: 39.3331,
    lng: -82.9824,
    category: "CEMETERY",
    country: "USA",
    city: "Chillicothe, Ohio",
    description: "A functioning cemetery built around a 2,000-year-old Hopewell burial mound — the largest concentration of generals' graves in America.",
    legend: "The 30-foot Hopewell mound at the centre predates the cemetery by 2,000 years. When the mound was excavated in 1838, it contained the remains of over 100 people and elaborate grave goods. The Hopewell culture built mounds aligned to lunar and solar cycles with a precision not understood to this day. Revolutionary War veterans buried here reportedly appear to visitors as translucent figures in tricorn hats, apparently still guarding the older mound.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // ── Australia & Pacific ───────────────────────────────────────────────────
  {
    id: "69",
    name: "Monte Cristo Homestead",
    slug: "monte-cristo-homestead",
    lat: -34.5833,
    lng: 148.5667,
    category: "HAUNTED_HOUSE",
    country: "Australia",
    city: "Junee, New South Wales",
    description: "Australia's most haunted house — six deaths in six years, a caretaker chained in a stable for 40 years, and a ghostly woman at the window.",
    legend: "Built in 1885, Monte Cristo has the darkest history of any Australian property. A stable boy was pushed or fell from the balcony; a maid fell down the stairs; a child died mysteriously in the nursery; a man was shot; a woman burned to death; and a caretaker was kept chained in a cottage for 40 years. The ghost of Mrs Crawley — the original owner — is seen at the upstairs window, staring at visitors who approach the gate.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "70",
    name: "Port Arthur Historic Site",
    slug: "port-arthur",
    lat: -43.1419,
    lng: 147.8511,
    category: "ASYLUM",
    country: "Australia",
    city: "Tasmania",
    description: "The most feared convict penal station in the British Empire — and site of Australia's deadliest modern massacre in 1996.",
    legend: "From 1833, Port Arthur held the most 'incorrigible' of transported convicts under a new 'silent system' of total sensory deprivation — prisoners wore hoods, were forbidden to speak, and attended chapel staring at individual booths. The psychological damage was catastrophic. In April 1996, 35 people were killed here in a mass shooting. Both the convict-era and modern victims are said to still haunt the ruins, heard weeping during the ghost tours the site has operated since the 1980s.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "71",
    name: "Aradale Mental Asylum",
    slug: "aradale-asylum",
    lat: -37.2833,
    lng: 143.5500,
    category: "ASYLUM",
    country: "Australia",
    city: "Ararat, Victoria",
    description: "Australia's largest abandoned mental asylum — 13,000 people died within its walls over 130 years of operation.",
    legend: "Aradale opened in 1865 and at its peak housed 1,000 patients. Treatments included insulin shock therapy, lobotomies, and straitjackets. 13,000 patients died here — many buried in unmarked graves on the grounds. The ghost of Nurse Kerry is the most encountered presence, still making her nightly rounds. The J Ward maximum security section, which held the criminally insane, is considered the most active — prisoners were chained to walls in cells less than 2 metres wide.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  // ── More Europe ───────────────────────────────────────────────────────────
  {
    id: "72",
    name: "Zvíkov Castle",
    slug: "zvikov-castle",
    lat: 49.5023,
    lng: 14.1838,
    category: "HAUNTED_HOUSE",
    country: "Czech Republic",
    city: "Písek",
    description: "A 13th-century Czech castle haunted by the Zvíkov Devil — who makes cameras fail, animals uneasy, and guests sleepless.",
    legend: "Every attempt to photograph the Zvíkov tower fails — cameras malfunction, batteries drain instantly, and developed film shows only blurred light. Dogs refuse to enter the tower and horses bolt when approaching it. In the 15th century, a Swedish soldier who slept in the tower was found the next morning aged 30 years overnight. The castle has never been successfully photographed from the inside of the main tower.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "73",
    name: "Houska Castle",
    slug: "houska-castle",
    lat: 50.4936,
    lng: 14.6242,
    category: "HAUNTED_HOUSE",
    country: "Czech Republic",
    city: "Blatce",
    description: "A castle built not to keep enemies out, but to keep something in — constructed directly over a bottomless pit said to be a gateway to Hell.",
    legend: "Houska Castle was built in the 1200s with no stables, no fortifications, no water supply, and no kitchen — it had no defensive or residential purpose. It was built over a large fissure in the earth that locals called the gateway to Hell, from which dark half-animal creatures and winged beasts were said to emerge. The castle's chapel was built directly over the hole. During WWII, Nazi occultists conducted experiments here. The pit still exists, sealed under the chapel floor.",
    spookyScore: 5,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "74",
    name: "Czocha Castle",
    slug: "czocha-castle",
    lat: 51.0819,
    lng: 15.3089,
    category: "HAUNTED_HOUSE",
    country: "Poland",
    city: "Lower Silesia",
    description: "A Silesian castle with a legendary dungeon prisoner who died of starvation — his skeleton found still chained to the wall in 1930.",
    legend: "A prisoner held in the castle dungeon during the Thirty Years War was forgotten when his guard died. His skeleton was discovered in 1930, still chained to the wall, with scratch marks on the stone recording the passing days. His ghost is seen in the dungeon and on the battlements. During WWII the castle was used by the SS — occult symbols scratched into the cellar walls by prisoners remained when the Poles took over in 1945.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "75",
    name: "Eltz Castle",
    slug: "eltz-castle",
    lat: 50.2042,
    lng: 7.3366,
    category: "HAUNTED_HOUSE",
    country: "Germany",
    city: "Wierschem",
    description: "A perfectly preserved medieval castle that has never been conquered — home to the ghost of the Knight Agnes von Eltz.",
    legend: "The only notable death at Eltz was Agnes von Eltz, who according to legend went to battle in armour alongside the men after the castle was besieged. She died fighting and her ghost — a woman in silver armour — is seen walking the battlements at dusk. The castle is the only one in the Moselle Valley never captured, never damaged, and still owned by the same family after 33 generations — 850 years.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "76",
    name: "Raynham Hall",
    slug: "raynham-hall",
    lat: 52.7964,
    lng: 0.7642,
    category: "HAUNTED_HOUSE",
    country: "England",
    city: "Norfolk",
    description: "A Norfolk mansion famous for the 1936 photograph of the Brown Lady — one of the most credible ghost photographs ever taken.",
    legend: "The Brown Lady is Dorothy Walpole, who died in 1726 under disputed circumstances — locked away by her husband, possibly starved to death. She was seen repeatedly by guests in the 1800s, including King George IV who reportedly fled the house in the night. In September 1936, photographers from Country Life magazine captured a translucent figure descending the main staircase. The image has never been convincingly debunked and remains a touchstone of photographic ghost evidence.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "77",
    name: "Castle of Good Hope",
    slug: "castle-of-good-hope",
    lat: -33.9258,
    lng: 18.4291,
    category: "HAUNTED_HOUSE",
    country: "South Africa",
    city: "Cape Town",
    description: "The oldest surviving colonial building in South Africa — where a ghost has haunted the bell tower since 1948.",
    legend: "A soldier stationed at the castle in 1948 fell from the bell tower. Since then, a tall figure in period uniform walks the ramparts and has been seen jumping from the same spot repeatedly, disappearing before hitting the ground. The ghost of Governor Pieter Gysbert van Noodt — who sentenced seven men to hang on April 23, 1728, and died himself of a heart attack that same afternoon — is the other permanent resident. He is seen in the governor's quarters in formal Dutch colonial dress.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "78",
    name: "Corvin Castle",
    slug: "corvin-castle",
    lat: 45.7497,
    lng: 22.8892,
    category: "HAUNTED_HOUSE",
    country: "Romania",
    city: "Hunedoara",
    description: "A Gothic-Renaissance castle where Vlad the Impaler was allegedly imprisoned — complete with a torture chamber and a bear pit.",
    legend: "Vlad III of Wallachia — the real-life inspiration for Dracula — was reportedly imprisoned at Corvin Castle by Hungarian king John Hunyadi for 7 years. The castle contains a 28-metre deep well dug by Ottoman prisoners who were promised freedom upon its completion — and then executed. A Turk inscribed on the well wall: 'You have water but not soul.' The inscription is still visible. The castle's torture chamber and bear pit remain intact.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "79",
    name: "Bran Castle",
    slug: "bran-castle",
    lat: 45.5153,
    lng: 25.3672,
    category: "HAUNTED_HOUSE",
    country: "Romania",
    city: "Brașov",
    description: "The castle most associated with Dracula — though Vlad Tepeș likely only visited once, its appearance inspired Bram Stoker's imagination.",
    legend: "Bram Stoker never visited Romania — he based Dracula's castle on descriptions from travel books, and Bran matches perfectly. Vlad Tepeș may have been held here briefly. The castle was home to Queen Marie of Romania, who left instructions to have her heart buried on the property. Her heart was indeed buried here in a gold casket in 1938 — it was stolen in 1968 and later recovered, but some say a replacement was buried and the real heart is elsewhere.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "80",
    name: "Borgund Stave Church",
    slug: "borgund-stave-church",
    lat: 61.0456,
    lng: 7.8194,
    category: "URBAN_LEGEND",
    country: "Norway",
    city: "Lærdal",
    description: "A perfectly preserved Viking-age wooden church from 1180 — with dragon heads and runic graffiti warning of the dead who won't stay buried.",
    legend: "The church is covered in protective dragon-head carvings to ward off evil spirits — a Christian building using pre-Christian magic. Inside, runic graffiti scratched by medieval visitors includes 'Thorir carved these runes on the eve of Kristmesse' and warnings about draugar — the undead of Norse belief who leave their graves to haunt the living. The churchyard contains graves marked with unusual runestones still not fully deciphered.",
    spookyScore: 3,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },

  {
    id: "30",
    name: "Overtoun Bridge",
    slug: "overtoun-bridge",
    lat: 55.9618,
    lng: -4.4361,
    category: "CURSED_PLACE",
    country: "Scotland",
    city: "Dumbarton",
    description:
      "A Victorian bridge where over 600 dogs have inexplicably leapt to their deaths — always from the same spot, always on clear days.",
    legend:
      "Since the 1950s, dogs crossing Overtoun Bridge have leapt from the exact same parapet — the right side between the last two parapets — at a rate of about one per month. Many survive and attempt to jump again. Local legend says the bridge is a 'thin place' where the barrier between the living and the dead is weak. The ghost of the White Lady of Overtoun has been seen nearby. Animal behaviourists have no definitive explanation.",
    spookyScore: 4,
    images: [],
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
];
